In [2]:
import numpy as np

In [3]:
a = [1,2,3,4]
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
b = np.array([1,2,3,4])
b*3

array([ 3,  6,  9, 12])

## Numpy

In [7]:
a = np.arange(1,10,2.5)
a

array([1. , 3.5, 6. , 8.5])

In [8]:
b = np.arange(1,13)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
c = np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [11]:
d = np.array([[1,2],[3,4]])
d

array([[1, 2],
       [3, 4]])

In [12]:
e = np.array([(1,2),(3,4)])
e

array([[1, 2],
       [3, 4]])

In [13]:
a = np.array([-1,0,1.0,100],dtype = "int8")
a

array([ -1,   0,   1, 100], dtype=int8)

In [14]:
a*2

array([ -2,   0,   2, -56], dtype=int8)

In [15]:
b = a.astype('float32')
b

array([ -1.,   0.,   1., 100.], dtype=float32)

In [16]:
a  = np.arange(12)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [18]:
b[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [19]:
# 1D - vector
# 2D - Matrix
# 3D - Tensor

#### tensor


In [64]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
c[1,1,1]

17

In [71]:
c[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [68]:
a**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [22]:
a+10

array([11, 12, 13, 14, 15])

In [23]:
a

array([1, 2, 3, 4, 5])

In [24]:
a<3

array([ True,  True, False, False, False])

In [25]:
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [26]:
a+b

array([ 6,  8, 10, 12, 14])

In [27]:
a*b

array([ 5, 12, 21, 32, 45])

In [28]:
a.dot(b)

115

In [29]:
b.dot(a)

115

In [72]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [74]:
c = np.arange(12).reshape(1,12)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [75]:
d = c.reshape(12,1)
d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [76]:
a*a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [77]:
d.dot(c)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22],
       [  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33],
       [  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55],
       [  0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66],
       [  0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77],
       [  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88],
       [  0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110],
       [  0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121]])

In [36]:
a = np.arange(3)
a.shape

(3,)

In [37]:
b = a.reshape(1,3)
b.shape

(1, 3)

In [38]:
c = b.reshape(3,1)
c.shape

(3, 1)

In [39]:
b.T

array([[0],
       [1],
       [2]])

In [40]:
# Vectorization - mapping
# masking - filtering

In [83]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [84]:
a>15

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [85]:
a[a>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
b= a.reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [87]:
b[b>15].reshape(7,2)

array([[16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

In [88]:
a = np.arange(30)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [47]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [48]:
b  = a.reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [49]:
b.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [50]:
c = a[:15]
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
c.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [52]:
a[0]=100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29])

In [53]:
b

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29]])

In [54]:
c

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [55]:
d = a[a>15]
d

array([100,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29])

In [56]:
d.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [57]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
b = a.reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### special arrays

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [61]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [63]:
np.ones(5)*5

array([5., 5., 5., 5., 5.])

In [20]:
np.empty((4,5))

array([[7.95287894e-312, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.69119330e-306],
       [5.30276956e+180, 1.57076922e-076, 4.57487963e-071,
        4.46156275e-086, 3.35810183e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 9.51799396e-047],
       [2.23112652e+160, 7.91340814e+165, 1.39426364e+165,
        5.57353928e-144, 1.50008929e+248]])

In [23]:
np.eye(3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.linspace(1,5,9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

## ANALYSIS

In [99]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
a.sum()

66

In [103]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
b.sum()

66

In [105]:
# axis 0 - rows, axis 1 - columns

In [106]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [74]:
b.sum(axis = 1)

array([ 6, 22, 38])

In [75]:
c = np.arange(24).reshape(4,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [76]:
c.sum(axis = 0)

array([[36, 40],
       [44, 48],
       [52, 56]])

In [77]:
c.sum(axis =1)

array([[ 6,  9],
       [24, 27],
       [42, 45],
       [60, 63]])

In [78]:
c.sum(axis = 2)

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33],
       [37, 41, 45]])

In [110]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
b.max(axis = 1)

array([ 3,  7, 11])

In [81]:
b.mean(axis = 0 )

array([4., 5., 6., 7.])

In [82]:
b.mean(axis = 1)

array([1.5, 5.5, 9.5])

In [83]:
np.median(b,axis = 0)

array([4., 5., 6., 7.])

In [84]:
np.std(b) # std deviation - how spread out is the data

3.452052529534663

In [85]:
b.mean()

5.5

## Random Distributions

In [129]:
90+np.random.randint(4,5)*10

130

In [135]:
np.random.randint(50,60,5)

array([55, 56, 58, 53, 57])

In [146]:
np.random.seed(32)
np.random.rand()

0.8588892672930397

In [152]:
mu = 100
sigma = 15
s = np.random.normal(mu,sigma,100)
s

array([113.50066781,  68.82781597, 102.59558577, 110.19325459,
        87.76635354, 102.89356858, 119.44413091,  81.50431776,
       127.093375  ,  69.32906957, 110.84919145, 124.72131297,
       101.2634851 ,  90.79727594, 103.63440795, 102.35589128,
        66.36007214,  72.62927801,  87.85570326, 107.49215938,
        81.14053587, 101.97284933,  96.87034379,  98.68199581,
       111.35570112,  83.02022272, 110.46103947, 115.13315755,
        98.91683318,  68.95664955,  71.71142873, 103.38708978,
       105.0069929 ,  99.61897016,  62.17040827, 100.42121681,
       109.95366786, 106.2436016 ,  96.77401632, 121.74732543,
        99.86753461,  99.19028973, 115.09504472,  75.45924343,
        84.66473336, 103.66774454,  66.84770718, 104.89685354,
        94.55258675, 121.21108105, 107.4416451 ,  81.8879316 ,
        79.84025776, 112.33415938,  98.79672808,  83.67005995,
        78.11165309,  74.77867107,  78.04242387,  86.91464662,
        68.52197494, 124.19028256, 110.44749818, 114.76

In [153]:
np.mean(s)

97.94902281640285

In [91]:
np.std(s)

16.261924039607752

In [92]:
d = np.random.randint(1,9, (3,4) )
d

array([[2, 6, 5, 7],
       [6, 7, 8, 8],
       [6, 6, 2, 7]])

In [147]:
d.sort()
d

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [148]:
d = d.flatten()

In [149]:
d.sort()
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [150]:
d.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])